### ISSUE TITLE
Compatibility with Cobo

### ISSUE THREAD

**Issue by thefonseca** [KeystoneHQ/Keystone-cold-app-btc#3]
Will Keystone releases be fully compatible with Cobo Vault Pro? (especially regarding the upgrade from Multi-coin to BTC-only)

**Comment by aaronisme** [comment]
you mean whether Cobo Vault can migrate to Keystone firmware?

**Comment by thefonseca** [comment]
Ok, that’s really sad to know, but thanks for sharing this information!

**Comment by aaronisme** [comment]
We are also sorry for that. we hope to provide the migration file but unfortunately  we can't do that.
